name: "Fetch Secrets"
description: "Fetch secrets from Doppler based on branch"

inputs:
  environment:
    description: "Environment"
    required: true
  doppler_develop_token:
    description: "Doppler Develop Token"
    required: false
  doppler_staging_token:
    description: "Doppler Staging Token"  
    required: false
  doppler_production_token:
    description: "Doppler Production Token"
    required: false

runs:
  using: "composite"
  steps:
    # Fetch develop secrets
    - name: Fetch develop secrets
      if: inputs.environment == 'dev'
      uses: dopplerhq/secrets-fetch-action@v1.2.0
      with:
        inject-env-vars: true
        doppler-token: ${{ inputs.doppler_develop_token }}

    # Fetch staging secrets
    - name: Fetch staging secrets
      if: inputs.environment == 'staging'
      uses: dopplerhq/secrets-fetch-action@v1.2.0
      with:
        inject-env-vars: true
        doppler-token: ${{ inputs.doppler_staging_token }}

    # Fetch production secrets
    - name: Fetch production secrets
      if: inputs.environment == 'prod'
      uses: dopplerhq/secrets-fetch-action@v1.2.0
      with:
        inject-env-vars: true
        doppler-token: ${{ inputs.doppler_production_token }}
